# Generated by Django 5.2.2 on 2026-05-22 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Senior Frontend Engineer (React/Vue)', max_length=200)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('Product Management', 'Product Management'), ('Training Services', 'Training Services')], default='Engineering', max_length=100)),
                ('location', models.CharField(help_text='e.g. Remote / Noida, Noida Office, Hybrid', max_length=150)),
                ('job_type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=50)),
                ('salary', models.CharField(help_text='e.g. $80,000 - $110,000 or $60 - $80 / hr', max_length=100)),
                ('tags', models.CharField(blank=True, help_text="Comma-separated list of keywords, e.g. 'React, TypeScript, CSS, SEO'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed responsibilities, expectations, and benefits.')),
                ('is_active', models.BooleanField(default=True, help_text='Toggle this off to hide the job listing from the Careers page.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('experience_years', models.DecimalField(decimal_places=1, help_text='Total years of work experience, e.g., 3.5', max_digits=4)),
                ('portfolio_link', models.URLField(blank=True, help_text='Link to candidate portfolio, GitHub, or LinkedIn', null=True)),
                ('resume_file', models.FileField(help_text='Uploaded CV/Resume file (PDF, DOC, DOCX)', upload_to='resumes/%Y/%m/')),
                ('cover_note', models.TextField(blank=True, help_text='Optional message or cover note from candidate', null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(help_text='The role applied for', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='careers.job')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
