# Generated by Django 5.2.2 on 2026-05-22 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=150)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=20)),
                ('client_company', models.CharField(blank=True, max_length=150, null=True)),
                ('inquiry_subject', models.CharField(max_length=200)),
                ('inquiry_message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client Inquiry',
                'verbose_name_plural': 'Client Inquiries',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
